import type { Metadata } from "next";
import {
  Laila,
  Julee,
  Keania_One,
  Bungee,
  Smooch_Sans,
} from "next/font/google";
import "./globals.css";

import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const laila = Laila({
  variable: "--font-laila",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

const julee = Julee({
  variable: "--font-julee",
  weight: "400",
  subsets: ["latin"],
});

const keania = Keania_One({
  variable: "--font-Keania_One",
  weight: "400",
  subsets: ["latin"],
});
const bungee = Bungee({
  variable: "--font-Bungee",
  weight: "400",
  subsets: ["latin"],
});

const smooch_Sans = Smooch_Sans({
  variable: "--font-Smooch_Sans",
  weight: "100",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${laila.variable} ${julee.variable} ${keania.variable} ${bungee.variable} ${smooch_Sans.variable} antialiased min-h-screen bg-custom-bg overflow-x-hidden`}
      >
        <div className="flex flex-col justify-between min-h-screen">
          <Header />
          <div className="sm:h-full md:h-[100%]">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
